sudo: false
language: node_js
node_js:
  - 16.16 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - npm install
  - npm run build # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: main
  local-dir: public
